version: "3.8"

services:
  db:
    image: postgres:15
    container_name: hansan-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hansanpension_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hansan-net

  app:
    build: .
    container_name: hansan-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hansanpension_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      JWT_SECRET: 4e5758fd289c4b7cbb51c02bced6b734
    networks:
      - hansan-net

volumes:
  pgdata:

networks:
  hansan-net:
