spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}

jpa:
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      format_sql: true
  show-sql: true

# Swagger 관련 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

logging:
  level:
    io.netty: DEBUG

netty:
  resolver:
    dns:
      use-native: false