spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hansanpension_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # ??? ??
  jackson:
    time-zone: Asia/Seoul
